Numpy se trata de un paquete fundamental para la computación científica con Python. Entre una gran conjunto de herramientas Numpy contiene:

1. Los objetos de tipo array que se tratan de objetos muy potentes para trabajar en N-dimensiones.
2. Sofisticadas funciones.
3. Herramientas integradas en C/C++ y Fortran.
4. Utilidades para Algebra lineal, transformada de Fourier, y capacidades para trabajar con números aleatorios.

# Your first Numpy Array

A continuación vamos a crearnos una lista que contiene la altura de distintos jugadores de beísbol en cm. El objetivo pasar esta lista a numpy array.

In [3]:
#Importamos la librería 
import numpy as np
#Nos creamos la lista
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
#A partir de la lista baseball nos creamos un numpy array 
np_baseball = np.array(baseball)
#Vemos el tipo de np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


# Baseball player's height

A continuación disponemos de una lista que contiene algunas medidas de jugadores de beísbol. Resulta que esta medida se encuentra en pulgadas y nuestro objetivo es pasarlas a metros. Para ello debemos de hacer uso de Numpy arrays.

In [5]:
#Nos creamos la lista de la altura en pulgadas
height = [74,74,72,72,73,69,69,71,76,71,73,73,74,74,69,70]
#Pasamos esta lista a tipo Numpy
np_height = np.array(height)
#Mostramos el resultado
print(height_np)

[74 74 72 72 73 69 69 71 76 71 73 73 74 74 69 70]


In [8]:
#Pasamos a metros la altura
np_height_m = np_height * 0.0254
#Mostramos el resultado
print(np_height_m)

[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778 ]


# Baseball player's BMI

A continuación nos proporcionan información respecto al peso de dichos jugadores en libras. Se nos pide calcular el índice de mas corporal de cada uno de los jugadores.

In [9]:
#Nos creamos la lista con el peso 
weight = [180,215,210,210,188,176,209,200,231,180,188,180,185,160,180,185]
#Pasamos a tipo Numpy
np_weight = np.array(weight)
#Pasamos las libras a kg
np_weight_kg = np_weight * 0.453592
#Calculamos el índice de masa coorporal de cada jugador
bmi = np_weight_kg / np_height_m ** 2
#Mostramos el resultado 
print(bmi)

[23.11037639 27.60406069 28.48080465 28.48080465 24.80333518 25.99036864
 30.86356276 27.89402921 28.11789135 25.10462629 24.80333518 23.7478741
 23.75233129 20.54255679 26.58105883 26.54444207]


# Lightweight baseball players

Para realizar la selección de un elemento en un Numpy Array, hacemos uso de los corchetes. 

In [13]:
#Seleccionamos el primer elemento del array bmi
print(bmi[0])

23.11037638875862


In [15]:
#Seleccionamos las 4 primeros elementos del array bmi
print(bmi[:4])

[23.11037639 27.60406069 28.48080465 28.48080465]


Podemos hacer uso de boolean Numpy Arrays para seleccionar elementos. Por ejemplo supongamos que queremos seleccionar aquellos jugadores que tienen un bmi inferiro a 21. Al hacer bmi < 21 esto retornará un array booleana de forma que si le pasamos a bmi dicha array booleana seleccionara solo aquellos elementos que cumpla la condición deseada

In [17]:
#Seleccionamos la altura de aquellos jugadores que tienen un bmi inferior a 21
print(np_height_m[bmi < 21])

[1.8796]


Es muy importante tener encuenta que un Numpy Array no puede contener elementos de distinto tipo. En caso de que esto ocurra se produce la coerción y lo que ocurrer es que todos los elementos de nuestro Numpy Array pasarán a ser strings.

# Your first 2D Numpy Array 

A continuacón vamos a crear una lista de listas, donde cada una de las listas contiene la altura y el peso de un determinado jugador de beísbol.

In [1]:
#Importamos numpy
import numpy as np
#Nos creamos la lista
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
#Nos creamos un Numpy Array de tipo 2D
np_baseball = np.array(baseball)
#Mostramos el tipo
print(type(np_baseball))
#Mostramos el tamaño
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


# Subsetting 2D Numpy Arrays 

A la hora de seleccionar elementos de una matriz numpy 2D, tenemos dos posibles opciones:

1. matriz\[fila\]\[columna\]
2. matriz\[fila,columna\]

In [2]:
#Seleccionamos la primera fila y la segunda columna para seleccionar el peso del primer jugador
print(np_baseball[0][1])

78.4


In [4]:
#Seleccionamos la tercera fila y la primera columna para seleccionar la altura del tercer jugador
print(np_baseball[2,0])

210.0


In [5]:
#Seleccionamos la estatura de todos los jugadores
print(np_baseball[:,0])

[180. 215. 210. 188.]


In [6]:
#Seleccionamos la info del tercer y cuarto jugador
print(np_baseball[2:,:])

[[210.   98.5]
 [188.   75.2]]


# 2D Arithmetic

Al igual que en el caso de una dimensión podemos realizar operaciones aritméticas con las matrices 2D. A continuación vamos a proceder a realizar la conversión de pulgadas a metros y de libras a kg.

In [9]:
#Nos creamos la matriz de conversión
conversion = np.array([0.453592, 0.0254])
#Realizamos el producto
result = np_baseball * conversion
print(result)

[[81.64656   1.99136 ]
 [97.52228   2.60858 ]
 [95.25432   2.5019  ]
 [85.275296  1.91008 ]]
