In [2]:
import numpy as np 

# Definiendo una matriz

Podemos representar una matriz en Python como un array bidimensional, es decir, como un numpy array formado por una lista de listas.

In [3]:
#Generamos una matriz de dos filas y tres columnas
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


# Operaciones aritméticas con matrices

## Suma de matrices

Dos matrices de igual dimensión pueden ser sumadas para crear una nueva matriz. Los elementos de la matriz resultante son calculados como la suma de los elementos de dichas matrices. 

Para hacer la suma de dos matrices en Python podemos hacer uso directamente el operador suma.

In [5]:
#Nos generamos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Sumamos ambas matrices
print(A+B)

[[ 6  8]
 [10 12]]


## Resta de matrices

Al igual que la suma, dos matrices de igual dimensión pueden ser restadas para obtener una tercera matriz. Los elementos de la matriz resultante son calculados como la diferencia de los elementos de dichas matrices. 

Para hacer la resta de dos matrices en Python podemos hacer uso directamente el operador resta.

In [6]:
#Generamos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Restamos dos matrices
print(B-A)

[[4 4]
 [4 4]]


## Multiplicación de matrices (producto de Hadamard)

Dos matrices del mismo tamaño pueden ser multiplicadas, esto es a menudo conocido como producto elemento a elemento o producto de Hadamard. Cuando hablamos del producto de dos matrices esta operación no se trata de la operación más común.

Podemos realizar el producto de dos matrices en Python haciendo uso del operador producto.

In [7]:
#Generamos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])

#Hacemos el producto entre las dos matrices
print(A * B)

[[ 4 10]
 [18 28]]


## División de matrices

Dos matrices de igual dimensión pueden ser divididas entre sí. Los elementos de la matriz resultante son calculados como la división entre los elementos de cada una de las matrices.

Podemos realizar la división de dos matrices en Python haciendo uso del operador división.

In [8]:
#Generamos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Hacemos la división 
print(A/B)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Multiplicación de matrices (dot product)

La multiplicación de matrices, también conocida como dot product, es la operación más común cuando hablamos del producto de matrices.

Para que dos matrices puedan realizar este tipo de operación debe cumplirse una regla: el número de columnas en la matriz A debe ser igual al número de filas de la matriz B.

Para realizar esta operación podemos hacer uso del operador **dot()** que ofrece Numpy.

In [10]:
#Generamos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Hacemos el dot product
print(A.dot(B))

[[19 22]
 [43 50]]


## Multiplicación entre matrices y vectores 

Una matriz y un vector pueden ser multiplicados siempre y cuando se cumpla que el número de columnas de nuestra matriz debe ser igual al número de elementos del vector.

Para ejecutar el producto entre una matriz y un vector podemos hacer uso de la función **dot()**.

In [11]:
#Nos generamos una matriz y un vector
A = np.array([[1, 2], [3, 4]])
v = np.array([2, 3])

#Hacemos el producto
print(A.dot(v))

[ 8 18]


## Multiplicación de una matriz por un escalar

Una matriz puede ser siempre multiplicada por un escalar, dando lugar a la misma matriz pero con todos sus elementos multiplicados por dicho escalar.

Para realizar el producto entre un escalar y una matriz en Python podemos hacer uso del operador producto

In [12]:
#Generamos una matriz
A = np.array([[1, 2], [3, 4]])

#Hacemos el producto de nuestra matriz por un escalar
print(A*2)

[[2 4]
 [6 8]]
