In [18]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank

# Transpuesta

Dada una matriz definida, su transpuesta se trata de una nueva matriz donde el número de filas y columnas son flipeadas. Se define mediante como: $$C = A^T$$

Esta operación no tiene ningún tipo de efecto si nuestra matriz es simétrica.

Numpy dispone del atributo **T** que nos permite obtener la transpuesta de una matriz.

In [8]:
#Generamos una matriz 
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
#Generamos la transpuesta
A_T = A.T
print(A_T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


# Inversa

La operación inversa se trara de un proceso que dada una matriz encuentra otra matriz que al multiplicarla por la matriz original da lugar a la matriz identidad. Es decir dada una matriz A, buscamos una matriz B que al multiplicarla por la matriz A da lugar a la matriz identidad.

$$AB = BA = I^n$$

La operación de invertir una matriz es indicada mediante el superíndice -1.

$$B = A^{-1}$$

No todas las matrices son invertibles, las matrices cuadradas que no son invertibles son conocidas como matrices singulares.

Numpy dispone de la función **inv()** que nos permite obener la inversa de una matriz existente.

In [10]:
#Generamos una matriz
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [11]:
#Calculamos su inversa
A_inv = inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
#Hacemos el producto
print(A.dot(A_inv))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# Traza 

La traza de una matriz cuadrada es la suma de los valores de la diagonal principal de la matriz. Esta operación se describe mediante la notación:

$$tr(A)$$

Numpy dispone de la función **trace()** que nos permite obtener la traza de una matriz cuadrada.

In [13]:
#Definimos una matriz 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#Calculamos su traza
print(np.trace(A))

15


# Determinante

El determinante de una matriz cuadrada es una representación escalar de el volumen de la matriz. De forma más específica el determinante de una matriz A nos indica el volumen de una caja donde sus lados están dados por las filas de A. El determinante de una matriz queda denotado mediante la notación:

$$det(A) = |A|$$

De forma técnica, el determinante es el producto de todos los eigenvalues de la matriz. Si el determinante de una matriz es nulo esto nos indica de forma clara que dicha matriz no tiene inversa.

Numpy dispone de la función **det()** que nos permite calcular el determinante de una matriz.

In [16]:
#Generamos una matriz
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [17]:
#Calculamos su determinante
print(det(A))

-2.0000000000000004


# Rango

El rango de una matriz es la estimación de el número de filas o columnas linealmente independientes en una matriz. Se denota mediante la expresión: 

$$rank(A)$$

El rango se estima de foma numérica, haciendo uso de la descomposición matricial. Un enfoque muy común es hacer uso de SVD (Singular-Value Descomposition).

Numpy nos proporciona la función **matrix_rank()** que nos permite calcular el rango de un array. Esta hace uso de la técnica SVD para estimar el rango.

In [19]:
#Generamos un vector
v1 = np.array([1, 2, 3])
#Calculamos el rango 
print(matrix_rank(v1))

1


In [20]:
#Generamos un vector de ceros
v2 = np.array([0, 0, 0, 0, 0])
#Calculamos el rango 
print(matrix_rank(v2))

0


In [21]:
#Generamo una matriz
A = np.array([[1, 2], [3, 4]])
print(matrix_rank(A))

2
