In [2]:
import numpy as np 
from IPython.display import Image

# Introducción

Los tensores son un tipo de estructura de datos usados en algebra lineal, y como los vectores y matrices, podemos realizar operaciones aritméticas con tensores.

# Qué son los tensores

Un tensor es una generalización de vectores y matrices y es facilmente comprensible como un array multidimensional.

Un vector es un array unidemensional o un tensor de primer orden, una matriz es un array bidimensional o un tensor de segundo orden. La notación de los tensores es muy similar a la notación de las matrices.

Muchas de las operaciones que pueden ser realizadas con escalares, vectores, y matrices pueden ser reformuladas para realizarse con tensores. Son ampliamente usados en los campos de física e ingeniería. Algunas operaciones en el aprendizaje automático como en el campo de aprendizaje profundo (deep learning) son descritas mediante el uso de tensores.

# Tensores en Python

Como los vectores y matrices, los tensores pueden ser representados en Python como arrays N-dimensionales. Es decir, un tensor puede ser definido como un array formado por una lista de listas.

In [5]:
#Generamos un tensor 3x3x3
T = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
             [[10, 11, 12], [13, 14, 15], [16, 17, 18]], 
             [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


# Operaciones aritméticas con tensores

Al igual que con las matrices, podemos realizar operaciones elemento a elemento con tensores.

## Suma de tensores

La suma elemento a elemento de dos tensores con las mismas dimensiones, resulta un nuevo tensor de igual dimensión donde cada valor escalar es la suma con su pareja de tensor.

En Python podemos realizar esta suma de forma automática, haciendo uso del operador suma.

In [11]:
#Nos creamos dos tensores de dimensiones 3x3x3
A = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])


B = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

#Hacemos la suma
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


# Resta de tensores

La resta elemento a elemento entre dos tensores de igual dimensión, resulta un nuevo tensor con las mismas dimensiones donde cada valor es la diferencia con su pareja de tensor correspondiente.

En Python podemos realizar esta operación directamente haciendo uso del operador diferencia.

In [14]:
#Hacemos la diferencia entre los tensores  A y B definidos anteriormente
C = A -B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## Producto de Hadamard entre tensores

El producto elemento a elemento de un tensor con otro tensor de las mismas dimensiones resulta un nuevo tensor de las mismas dimensiones donde cada valor es el producto con su pareja de tensor correspondiente.

En Python podemos realizar esta operación directamente haciendo uso del operador producto.

In [15]:
#Hacemos el producto entre los tensores A y B definidos anteriormente
C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


## División de tensores

La división elemento a elemento de un tensor con otro tensor de igual dimensión resulta un nuevo tensor con las mismas dimensiones donde cada elemento es el cociente con su paraje correspondiente.

En Python podemos realizar esta operación directamente haciendo uso del operador división.

In [16]:
C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Producto de tensores

Dado un tensor con q dimensiones y un tensor B con r dimensiones, el producto de estos tensores será un nuevo tensor de orden q + r dimensiones.

El producto de tensores puede ser implementado en Numpy mediante la función **tensordot()**. La función toma como argumento los dos tensores a multiplicar y el eje en el cual la suma de productos es realizada, también conocida como suma reductora. Para calcular el producto de tensores el eje seleccionado debe ser el eje cero.

In [19]:
#Generamos el producto de tensores
C = np.tensordot(A, B, axes = 0)
print(C.shape)
print(C)

(3, 3, 3, 3, 3, 3)
[[[[[[  1   2   3]
     [  4   5   6]
     [  7   8   9]]

    [[ 10  11  12]
     [ 13  14  15]
     [ 16  17  18]]

    [[ 19  20  21]
     [ 22  23  24]
     [ 25  26  27]]]


   [[[  2   4   6]
     [  8  10  12]
     [ 14  16  18]]

    [[ 20  22  24]
     [ 26  28  30]
     [ 32  34  36]]

    [[ 38  40  42]
     [ 44  46  48]
     [ 50  52  54]]]


   [[[  3   6   9]
     [ 12  15  18]
     [ 21  24  27]]

    [[ 30  33  36]
     [ 39  42  45]
     [ 48  51  54]]

    [[ 57  60  63]
     [ 66  69  72]
     [ 75  78  81]]]]



  [[[[  4   8  12]
     [ 16  20  24]
     [ 28  32  36]]

    [[ 40  44  48]
     [ 52  56  60]
     [ 64  68  72]]

    [[ 76  80  84]
     [ 88  92  96]
     [100 104 108]]]


   [[[  5  10  15]
     [ 20  25  30]
     [ 35  40  45]]

    [[ 50  55  60]
     [ 65  70  75]
     [ 80  85  90]]

    [[ 95 100 105]
     [110 115 120]
     [125 130 135]]]


   [[[  6  12  18]
     [ 24  30  36]
     [ 42  48  54]]

    [[ 60  66  72]
     [