In [5]:
import numpy as np
from numpy.linalg import inv

# Matriz cuadrada 

Una matriz cuadrada es una matriz donde el número de filas y le número de columnas son iguales. El tamaño de una matriz cuadrada se le conoce como orden, de forma que una matriz de orden 4, se trata de una matriz de tamaño 4x4. Los elementos que forman la diagonal de la matriz,se les conoce como diagonal principal.

In [3]:
#Generamos una matriz cuadrada de orden 3
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


La matriz anterior se trata de una matriz cuadrada de orden 3, donde la diagonal principal está formada por los elementos: 1, 5, 9.

# Matriz simétrica

Una matriz simétrica se trata de un tipo de matriz cuadrada donde el triángulo superior derecho es igual al inferior izquierdo. Para ser simétrica, el eje de simetría es siempre la diagonal principal de la matriz.

In [4]:
#Generamos una matriz simétrica 
A = np.array([[1, 2, 3, 4, 5], [2,1, 2, 3, 4], [3, 2, 1, 2, 3], [4, 3, 2, 1, 2], [5, 4, 3, 2, 1]])
print(A)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


En una matriz simétrica siempre se cumple que la traspuesta de dicha matriz, es la propia matriz.

# Matriz triangular

Una matriz triangular es un tipo de matriz cuadrada donde todos sus valores por encima o por debajo de la diagonal principal son todos cero. Si los elementos que son cero son aquellos que están por debajo de la diagonal principal se le conoce como matriz triangular superior. Sin embargo, si los valores nulos son los elementos por encima de la diagonal principal se le conoce como matriz triangular inferior.

In [5]:
#Generamos una matriz diagonal superior
A = np.array([[1, 2, 3], [0, 1, 2], [0, 0, 3]])
print(A)

[[1 2 3]
 [0 1 2]
 [0 0 3]]


In [9]:
#Generamos una matriz diagonal inferior
A = np.array([[1, 0, 0], [1, 2, 0], [1, 2, 3]])
print(A)

[[1 0 0]
 [1 2 0]
 [1 2 3]]


Numpy dispone de funciones que nos permiten generar la matriz triangular de una matriz ya existente. 

La función **tril()** nos permite calcular la matriz triangular inferior de una matriz ya existente.

La función **triu()** nos permite calcular la matriz triangular superior de una matriz ya existen.

In [11]:
#Generamos una matriz cuadrada de orden 3
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#Generamos la matriz triangular inferior de la matriz A
print(np.tril(A))

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [14]:
#Generamos la matriz triangular superior de la matriz A 
print(np.triu(A))

[[1 2 3]
 [0 5 6]
 [0 0 9]]


# Matriz diagonal

Una matriz diagonal se trata de una matriz donde todos los elementos distintos de la diagonal principal son cero. Generalmente una matriz diagonal es conocida con la letra **D** aunque también puede ser representada de forma vectorial mediante un vector **d**.

In [15]:
#Generamos una matriz diagonal
D = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [16]:
#Generamos la representación vectorial de la matriz
d = np.array([[1], [2], [3]])
print(d)

[[1]
 [2]
 [3]]


Una matriz diagonal no tiene por qué ser cuadrada. En el caso de una matriz rectangular, la diagonal principal debería cubrir la dimensión más pequeña.

In [17]:
#Generamos una matriz diagonal no cuadrada
D = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4], [0, 0, 0, 0]])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]
 [0 0 0 0]]


Numpy dispone de la función **diag()** que nos permite generar la matriz diagonal de una matriz ya existente o bien transformar un vector existente en una matriz diagonal.

In [18]:
#Generamos una matriz
A = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(A)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [21]:
#Extraemos el vecto de nuestra matriz diagonal 
d = np.diag(A)
print(d)

[1 2 3]


In [22]:
#Generamos la matriz diagonal a partir del vector diagonal
D = np.diag(d)
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Matriz Identidad

Una matriz identidad es una matriz cuadrada que no cambia un vector cuando esta lo multiplica. Se trata de una matriz donde todos sus elementos son cero excepto los elementos de la diagonal principal que son unos. Es representada muy a menudo mediante la notación **I** o **In** donde n representa la dimensión de nuestra matriz identidad.

In [23]:
#Generamos la matriz identidad I3
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Numpy disponde de la función **identity()** que nos permite generar la matriz identidad de una dimensión n indicada.

In [24]:
#Generamos la matriz I3 mediante la función identity
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Matriz ortogonal

Dos vectores son ortogonales cuando su producto es igual a cero. Si la longitud de cada vector es la unidad, entonces además reciben el nombre de ortonormales.

Es intuitivo considerar que una línea es ortogonal con otra si estas son perpendiculares. Una matriz ortogonal es un tipo de matriz cuadrada cuyas columnas y filas son vectores unitarios ortonormales. Estas matrices generalmente se denotan con **Q**.

Se dice que una matriz es ortogonal si su transpuesta es igual a su inversa.

También se dice que una matriz es ortogonal si el producto de la propia matriz con su traspuesta es igual a la matriz identidad.

In [7]:
#Generamos una matriz ortogonal
Q = np.array([[1, 0], [0, -1]])

#Calculamos su transpuesta
Q_T = Q.T

#Calculamos su inversa
Q_inv = inv(Q)

#Comprobamos que nuestra matriz es ortogonal 
print(Q_inv == Q)
print(Q_T == Q_inv)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
