In [4]:
import numpy as np

# De lista de una dimensión a tipo de dato numpy array

Da una lista de una dimensión, podemos transformar a tipo de dato numpy array sin más que hacer uso de la función **array()**

In [5]:
#Generamos una lista de números enteros
lista = [10,9,8,7]
print(type(lista))

<class 'list'>


In [6]:
#Pasamos a tipo de datos numpy array
np_lista = np.array(lista)
print(type(np_lista))

<class 'numpy.ndarray'>


# Conviertiendo a tipo numpy array datos de dos dimensiones

En el campo del aprendizaje automático es muy común con datos de dos dimensiones, donde cada fila suele ser una observación y cada columna se trata de una nueva característica. Este tipo de datos, pueden ser vistos como una lista de listas, donde cada lista se trata de una observación. Para transformar una lista de listas en un tipo de dato numpy array, basta con hacer uso de la función **array()**.

In [7]:
#Nos creamos nuestra lista de listas
lista_2D = [[1,2], [3,4], [5,6]]
print(type(lista_2D))

<class 'list'>


In [8]:
#Pasamos a tipo de datos numpy array
np_lista_2D = np.array(lista_2D)
print(type(np_lista_2D))

<class 'numpy.ndarray'>


# Seleccionando elementos

La forma de seleccionar elementos en el lenguaje de programación Python es muy similar a otros lenguaje de programación como Jave, C# o C++.El principal dato que se debe tener en cuenta es que Python se trata de un lenguaje de programación cero indexado, es decir, el primer elemento de una lista, array, matriz etc se accede mediante el índice 0 y no mediante el índice 1 como pasa en el lenguaje de programación **R**.

## Seleccionando elementos en datos de una dimensión

Para acceder a los elementos de un elemento de una sola dimensión, se hace uso de los corchetes (**[]**), donde en su forma más sencilla recibe el índice del elemento al que deseamos acceder.

In [9]:
#Nos generamos un array
np_array = np.array([11,12,13,14,15])

#Accedemos al primer elemento 
print(np_array[0])

11


In [10]:
#Accedemos al segundo elemento 
print(np_array[1])

12


Otra de las novedades que aporta la seleccion de elementos en Python, es la posibilidad de hacer uso del indexado mediante números negativos. Es decir, nos permite seleccionar elementos de atrás adelante, en este caso, para acceder al último elemento de nuestro array podemos hacer uso del índice -1

In [11]:
print(np_array[-1])

15


## Seleccionando elementos en datos de dos dimensiones

La selección de elementos para tipos de dato de dos dimensiones es similar al caso de una sola dimensión, excepto que en el caso de dos dimensiones una coma es usada para separar cada una de las dimensiones.

In [12]:
#Seleccionamos el primer elemento de nuestro conjunto de datos
print(np_lista_2D[0,0])

1


Si estamos interesados en seleccionar todo los elementos de la primera fila podemos hacer uso de la notación (1,)

In [16]:
#Seleccionamos todos los elementos de la primera fila
print(np_lista_2D[(0,)])

[1 2]


# Slicing en numpy arrays

Las estructuras como listas o numpy arrays pueden ser "rebanadas". Esto signfica que una sub secuencia de la estructura puede ser seleccionada y recuperada. Para realizar este tipo de selección debemos de hacer uso del operador **:** mediante el siguiente formato: **data[from:to]**.Se debe tener en cuenta que el último índice no es seleccionado.

También podemos hacer uso de la notación **data[from:]** en este caso seleccionamos todos los elementos desde un índice hasta el final. 

La expresión **data[:to]** nos permite seleccionar todos los elementos desde el principio hasta un determinado valor(no incluido)

## Slicing para elementos de una dimensión

In [18]:
#Seleccionamos los tres primeros elementos
print(np_array[0:3])

[11 12 13]


In [19]:
#Seleccionamos los tres primeros elementos
print(np_array[:3])

[11 12 13]


In [21]:
#Seleccionamos todos los elementos desde un determinado elemento hasta el final
print(np_array[3:])

[14 15]


## Slicing para elementos de dos dimensiones

La forma de hacer slicing con datos de dos dimensiones es exactamento igual que para el caso de una sola dimensión ahora vemos un par de ejemplos.

In [22]:
#Nos generamos un nuevo array
datos = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])

In [23]:
#Seleccionamos de nuestros datos todos los elementos menos los elementos de la última columna
print(datos[:, :-1])

[[11 22]
 [44 55]
 [77 88]]


In [24]:
#Seleccionamos todos los datos de la última columna
print(datos[:, -1])

[33 66 99]


# Dimensionando nuestras arrays de forma adecuada

Algunas librerías como scikit-learn, requieren que el tamaño de nuestras arrays de una dimensión sean reescaladas a arrays de dos dimensiones. Algunos como algoritmos como LSTM, RNN, requieren que los inputs de sus arrays sean de tres dimensiones.

## De una dimensión a dos dimensiones

A la hora de hacer reshaping, numpy dispone de la función **reshape()**. Esta función toma un solo argumento que especifica el nuevo tamaño de nuestra array.

In [28]:
#Nos generamos un array
data = np.array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [30]:
#Hacemos el reshape 
data_reshape = data.reshape(data.shape[0], 1)
print(data_reshape.shape)

(5, 1)


## De dos dimensiones a tres dimensiones

En determinados algoritmos como LSTM hacer un reshape de datos de dos dimensiones a datos de tres dimensiones es algo bastante normal.

In [31]:
#Generamos nuestros datos 
data = [[11, 22],
[33, 44],
[55, 66]]

#Pasamos a tipo numpy array
data = np.array(data)
print(data.shape)

(3, 2)


In [32]:
#Convertimos nuestros datos a tres dimensiones
data = data.reshape(data.shape[0], data.shape[1], 1)
print(data.shape)

(3, 2, 1)
