In [1]:
import numpy as np

# Introducción  NumPy Arrays

Numpy se trata de una librería de Python que puede ser usada para aplicaciones numéricas y científicas. Se trata de la herramienta usada para realizar operaciones de algebra lineal.
La principal estructura de datos en Numpy es el **ndarray**, que es el nombre corto para un array N-dimensional. Un array tiene un tamaño fijo en memoria que contiene datos del mismo tipo, tales como enteros, floats, etc. 

## Creando nuestra primera Numpy Array

Una de las formas más sencillas a la hora crear un Numpy Array, es a partir de una lista (todos los elementos de esta lista deben de tener el mismo tipo de dato) junto con la función **array()**.

In [3]:
#Nos creamos un numpy array de numeros enteros
array_aux = np.array([1,2,3,4,5])
print(array_aux)

[1 2 3 4 5]


## Atributos dtype y shape

El atributo **dtype** nos permite conocer el tipo de dato soportado por nuestra numpy array. Por otro lado, el atributo **shape** nos permite saber la dimensión de nuestra array, este atributo nos retorna una tupla que contiene el número de filas y columnas de nuestra array.

In [4]:
#Vemos el tipo de dato soportado por nuestra array_aux
print(array_aux.dtype)

int64


In [5]:
#Vemos la dimensión de nuestra array_aux
print(array_aux.shape)

(5,)


## Funciones para crear arrays

Numpy dispone de una gran cantidad de funciones que nos permiten generar arrays de forma más conveniente.

### Empty

La función **empty()** nos permite crear un array de un tamaño que podemos especificar. El argumento que recibe esta función es una array o tupla donde se especifica la dimensión de nuestra array. Tras crear nuestra array esta contendrá valores aleatorios.

In [11]:
#Nos generamos un array mediante la función empty
a = np.empty((3,3))
print(a)

[[6.91427843e-310 4.68834590e-310 6.91426883e-310]
 [6.91426883e-310 6.91426883e-310 6.91426883e-310]
 [6.91426883e-310 6.91426883e-310 3.95252517e-322]]


Además del argumento principal que es la dimensión de nuestro ndarray, esta función nos permite seleccionar el tipo de dato que queremos que almacene nuestro array:

* **dtype**: nos permite especificar el tipo de datos que deseamos que contenga nuestra array inicializada.

In [15]:
#NOs generamos un array que toma valores enteros de 32 bits 
a_2 = np.empty((3,3), dtype = np.int32)
print(a_2)

[[-660857960      32583 -660857960]
 [     32583         32          0]
 [ 808797237  843399490         48]]


### Zeros

La función **zeros()** nos permite crear un array de un tamaño que podemos especificar. El argumento que recibe es un array o tupla donde se especifica la dimensión de nuestra array. Tras crear nuestra array esta contendrá todos sus valores a cero.

In [12]:
#Nos generamos un array mediante la función zeros
b = np.zeros([4,4])
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Además del argumento principal que es la dimensión de nuestro ndarray, esta función nos permite seleccionar el tipo de dato que queremos que almacene nuestro array:

* **dtype**: nos permite especificar el tipo de datos que deseamos que contenga nuestra array inicializada. Por defecto toma el valor de float64.

In [18]:
#Nos generamos un array de ceros de tipo int64
b_2 = np.zeros((4,4), dtype = np.int64)
print(b_2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Ones

La función **ones()** nos permiter crear un array de un tamaño que podemos especificar. El argumento que recibe es un array o tupla donde se especifica la dimensión de nuestra array. Tras crear nuestra array esta contrandrá todos sus valores a uno. 

In [13]:
#Nos generamos un array mediante la función ones
c = np.ones((2,2))
print(c)

[[1. 1.]
 [1. 1.]]


Además del argumento principal que es la dimensión de nuestro ndarray, esta función nos permite seleccionar el tipo de dato que queremos que almacene nuestro array:

* **dtype**: nos permite especificar el tipo de datos que deseamos que contenga nuestra array inicializada. Por defecto toma el valor de float64.

In [19]:
#Nos generamos un array de unos de tipo int8
c_2 = np.ones([2,2], dtype = np.int8)
print(c_2)

[[1 1]
 [1 1]]


## Combinando arrays

Numpy nos proporciona una gran variedad de funciones para crear nuevas arrays a partir de arrays ya existentes.

### Vertical stack (vstack())

Dadas dos o más arrays existentes podemos apilar de forma vertical dichas arrays haciendo uso de la función **vstack()**. Esta función recibe como argumento un array o tupla que contiene las arrays que queremos apilar.

In [24]:
#Nos generamos dos arrays
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

#Las apilamos de forma vertical mediante vstack
array_vstack = np.vstack((array1, array2))
print(array_vstack)

[[1 2 3]
 [4 5 6]]


Para que dos arrays puedan ser apiladas de forma vertical ambas deben de contener el mismo número de columnas.

### Horizontal stack (hstack())

Dadas dos o más arrays existentes podemos apilar de forma horizontal dichas arrays haciendo uso de la función **hstack()**. Esta función recibe como argumento un array o tupla que contiene las arrays que queremos apilar.

In [34]:
#Nos generamos dos arrays
array1 = np.ones((3,2))
array2 = np.zeros((3,2))

#Las apilamos de forma horizontal mediante hstack
array_hstack = np.hstack([array1, array2])
print(array_hstack)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


Para que dos o más arrays puedan ser apiladas de forma horizontal ambas deben de contener el mismo número de filas