In [12]:
import numpy as np 
from scipy.linalg import lu, qr, cholesky

La descomposición matricial son métodos que reducen una matriz en partes que hace que sea más fácil realizar operaciones complejas. Los métodos de descomposición de matrices, también llamados métodos de factorización, son fundamentales en el algebra lineal computacional.

# Que es la descomposición matricial

La descomposición matricial es una forma de reducir una matriz en partes. Este es un enfoque que puede simplificar operaciones matriciales complejas que pueden ser realizadas sobre la matriz descompuesta en lugar de sobre la matriz original. Existen muchas formas de descomponer una matriz.

# Descomposición LU

La descomposición LU es usada en matrices cuadradas y descompone la matriz en dos componentes L y U.

$$A = LU$$

Donde A es la matriz cuadrada que deseamos descomponer, L es el triángulo matricial inferior y U es el triángulo matricial superior. Los factres L y U son matrices triangulares.

La descomposición LU se encuentra haciendo uso de un proceso numérico iterativo y puede fallar en aquellas matrices que no se pueden descomponer o no pueden ser descompuestas fácilmente. Una variación de esta descomposición que es numéricamente más estable, la llamada descomposición LUP.

$$ A = PLU $$

Las filas de la matriz original son re-ordenadas para simplificar el proceso de descomposición y la matriz adicional P especifica una forma de permutar el resultado y retornar el resultado al orden original. Existen otras variciones del método LU.

La descomposición LU es a menudo usada para simplificar la resolución de sistemas ecuaciones, tales como encontrar los coeficientes de una regresión lineal, o calcular el determinante o la inversa de una matriz.

La descomposición LU puede ser implementada en Python mediante la función **lu()**. De forma más específica esta función calcula la descomposición PLU.

In [3]:
#Generamos un array 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Descomponemos nuestra array en las tres componentes
P, L, U = lu(A)

#Mostramos los resultados 
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [4]:
#Reconstruimos la matriz a partir de la descomposición
B = P.dot(L).dot(U)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Descomposición QR

La descomposición QR es usada para matrices de tamañao mxn, es decir, no está limitada a matrices cuadrada. Descompone una matriz en las componentes Q y R.

$$A = QR$$

Donde A es la matriz que deseamos descomponer, Q es una matriz de tamaño mxm y R es la matriz triangular superior de tamaño mxn. La descomposición QR es encontrada mediante un proceso numérico iterativo que puede fallar para aquellas matrices que no pueden ser descompuestas, o no pueden ser descompuestas de forma sencilla. Esta descomposición es a menudo usada para resolver sistemas de ecuaciones lineales.

La descomposición QR puede ser implementada en Python haciendo uso de la función **qr()**. Por defecto retorna las matrices Q y R con las dimensiones más pequeñas. Podemos cambiar esto de forma que nos retorne las matrices Q y R esperadas, especificando el argumento **complete**.

In [10]:
#Generamos un array
A = np.array([[1,2], [3,4], [5,6]])

#Hacemos la descomposicion
Q, R = qr(A)
print(Q)
print(R)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [11]:
#Recuperamos la matriz original 
B = Q.dot(R)
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Descomposición de Cholesky

La descomposición de Cholesky es aplicada sobre matrices cuadradas donde todos sus valores son positivos, también conocidas como matrices definidas positivas. Nos centraremos en la  descomposición de matrices reales.

$$A = LL{^T}$$

Donde A es la matriz que deseamos factorizar, L es la matriz triangular inferior y LT es la transpuesta de L. La descomposición también puede ser definida como el producto de la matriz triangular superior.

$$A=UU{^T}$$

La descomposición de Cholesky es usada para resolver mínimos cuadrados para la regresión lineal, así como métodos de simulación y optimización. Cuando trabajamos con matrices simétricas, la descomposición de Cholesky es dos veces más rápida y eficiente que la descomposición LU y debería ser usada en estos casos.

La descomposición de Cholesky puede ser calculada en Python haciendo uso de la función **cholesky()**. Esta función retorna la matriz L, si queremos acceder a su traspuesta podemos acceder de forma bastante sencilla.

In [13]:
#Generamos un array
A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])

#Obtenemos la descomposición mediante cholesky
L = cholesky(A)
print(L)

[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]


In [17]:
#Obtenemos la matriz original 
B = L.T.dot(L)
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
