In [9]:
import numpy as np 
from numpy.linalg import eig, inv

La descomposición matricial es una herramienta útil para reducir una matriz en sus partes constituyentes con el objetivo de simplificar operaciones complejas. Quizás el tipo o método más usado a la hora de descomponer una matriz es la descomposición en vectores y valores propios.

# Eigendecomposition de una matriz 

La eigendecomposition de una matriz se trata de un tipo de descomposición que implica descomponer una matriz cuadrada en un conjunto de vectores y valores propios.

Un vector es un vector propio de una matriz si satisface la que:

$$Av = \lambda v$$

Donde A es la matriz cuadrada que deseamos descomponer, v es el vector propio y lambda es un valor propio que se trata de un escalar.

Una matriz puede tener un vector propio y un valor propio para cada dimensión de la matriz original. No todas las matrices cuadradas pueden ser descompuestas en vectores y valores propios, y algunas solo pueden ser descompuestas de forma que los números complejos son requeridos. La matriz original puede ser vista como el producto de los vectores propios y de los valores propios.

$$ A = Q\lambda Q^{-1}$$

Donde Q es la matriz de los vectores propios y lambda es la matriz diagonal de los valores propios.

Como otros métodos de descomposición matricial, la Eigendecomposition es usada como un elemento para simplificar los cálculos matriciales complejos.

Cuando un vecto es multiplicado por la matriz A lo más normal es que cambie de dirección. Ciertos vectores excepcionales **x** están en la misma dirección **Ax**. Estos son los vectores propios. Multiplicar un vector propio por A, nos da un vector **Ax** que es lambda veces el vector original.

El valor propio lambda indica si el vector **x** se estira, se comprime o se invierte o si no se modifica, cuando es multiplicado por A.

# Valores propios y Vectores propios

Los vectores propios son vectores unitarios, lo que significa que su longitud y magnitud es igual a la unidad. SOn referidos en ocasiones como vectores rectos, lo que simplemente significa un vector columna.

Los valores propios son coeficientes aplicados a los vectores propios que dan la magnitud y la longitud de un vector.

# Calculando la descomposición en vectores y valores propios

Esta descomposición se realiza haciendo uso de un algoritmo iterativo muy eficiente del cual no vamos a dar detalles. Para realizar esta descomposición Python dispne de la función **eig()**.

In [2]:
#Generamos un array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Generamos la descomposición 
values, vectors = eig(A)
print(values)
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# Confirmar vectores y valores propios

Se puede determinar si un vector es en efecto un vector propio de una matriz. Para hacer esto multiplicamos el vector propio candidato por el vector de valores y comparamos el resultado con los valores propios.

In [6]:
#Generamos un array 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Generamos la descomposición en vectores propios y valores propios
values, vectors = eig(A)

#Vemos si el primer vector propio es realmente un vector propio
B = A.dot(vectors[:, 0])
C = values[0]*vectors[:, 0]
print(B)
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


# Reconstruyendo la matriz original

A partir de los valores propios y de los vectores propios podemos reconstruir la matriz original. En primer lugar, la lista de vectores propios debe ser transformada a una matriz donde cada fila de dicha matriz es un vector propio. En segunda lugar los valores propios deben ser transformados a una matriz diagonal. Tras esto, debemos de calcular la inversa de la matriz de vectores propios. Finalmente hacemos el produco de las dos matrices.

In [13]:
# Generamos un array 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Hacemos la descomposicion
values, vectors = eig(A)

#Creamos la matriz inversa de nuestra matriz de vectores
vectors_inv = inv(vectors)

#Generamos la matriz diagonal a partir de los valores propios
values_diag = np.diag(values)

#Hacemos el producto
print(vectors.dot(values_diag).dot(vectors_inv))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
