In [1]:
import numpy as np 

# Introducción 

Los vectores son un elemento fundamental del algebra lineal. Los vectores son usados en todo el campo del machine learning, tanto en la descripción de algoritmos como en el tipo de dato necesario para entrenar nuestros algoritmos. 

Un vector es una tupla de uno o más valores llamados escalares. Las vectores normalmente son representados mediante letras minúsculas, de la forma **v = (v1,v2,v3)** donde **v1,v2,v3** son valores escalares, a menudo números reales.

# Definiendo un vector 

En Python un vector puede ser representado mediante un numpy array

In [2]:
#Nos generamos nuestro primer vector
v = np.array([1,2,3])
print(v)

[1 2 3]


Este ejemplo define un vector de tres elementos, donde cada uno de sus elementos es un número real.

# Operaciones aritméticas con vectores

Las operaciones aritméticas en un vector son realizadas elemento a elemento, de forma que las operaciones entres dos vectores de igual longitud dan lugar a otro vector de igual longitud.

## Suma de vectores

Dos vectores de igual longitud pueden ser sumados juntos para crear un tercer vector. El nuevo vector tendrá la misma longitud que los otros dos vectores. Cada uno de los elementos del nuevo vector es calculado como la suma de los elementos de los otros vectores que se encuentran en el mismo índice.

In [4]:
#Nos generamos dos vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Hacemos la suma
print(a+b)

[5 7 9]


## Diferencia de vectores

Dos vectores de igual longitud pueden ser restados con el objetivo de obtener un tercer vector. Al igual que la suma, el vector resultante tendrá la misma longitud que los vectores que actuaron en la operación. Cada uno de los elementos del nuevo vector es calculado como la resta de los elementos de los otros vectores que se encuentran en el mismo indice.

In [5]:
#Nos generamos dos vectores
a = np.array([9, 8, 7])
b = np.array([6, 5, 4])

#Hacemos la resta
print(a-b)

[3 3 3]


## Producto de vectores

Dos vectores de igual longitud pueden ser multiplicados juntos con el objetivo de obtener un tercer vector. Este vector resultante tendrá la misma longitud y se obtendrá como el producto elemento a elemento de cada uno de los elementos de los vectores.

In [6]:
#Nos generamos dos vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Hacemos el producto
print(a*b)

[ 4 10 18]


## División de vectores

Dos vectores de igual longitud pueden ser divididos con el objetivo de obtener un tercer vector. Este vector resultante tendrá la misma longitud que los vectores que pertenecen a la operación y además se obtendrá como el cociente elemento a elemento de cada uno de los vectores.

In [7]:
#Nos generamos dos vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Hacemos el cociente
print(a/b)

[0.25 0.4  0.5 ]


## Dot product

El **dot product** se trata de una operación que multiplica los elementos de dos vectores entre sí y tras esto suma los resultados obtenidos en el producto, es decir, el resultado de esta operación es un escalar. Esta operación es la clave para calcular proyecciones de vectores, descomposición de vectores y determinar ortogonalidad. 

Python nos permite realizar esta operación mediante la función **dot()**.

In [8]:
#Nos genramos dos vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Hacemos el dot product
print(a.dot(b))

32


## Multiplicación de un vector por un escalar

Un vector puede ser multiplicado por un escalar. Dicha multiplicación es realizada sobre cada elemento del vector, lo que da lugar a un nuevo vector escalado de igual longitud.

In [9]:
#Nos generamos un vector
a = np.array([1, 2, 3])
s = 2

#Hacemos el producto del vector por el escalar
print(a*s)

[2 4 6]
